export enum ActionsType {
  ADD_TODO_ITEM = "ADD_TODO_ITEM",
  REMOVE_TODO_ITEM = "REMOVE_TODO_ITEM",
  TOGGLE_TODO = "TOGGLE_TODO",
  UPDATE_PREFERENCES = "UPDATE_PREFERENCES",
}

export const actions = {
  ADD_TODO_ITEM: "ADD_TODO_ITEM",
  REMOVE_TODO_ITEM: "REMOVE_TODO_ITEM",
  TOGGLE_TODO: "TOGGLE_TODO",
  UPDATE_PREFERENCES: "UPDATE_PREFERENCES",
};
